---
title: "Results Section Two"
description: "Project description here"
tags: ["R", "collapsibleTree"]
weight: 3
draft: false
output: html_document
---

One this page you may want to go more in-depth into one part of your project. For example, if you created isochrones or made an interactive map, you could highlight that here. 

### Framing the Problem 

Here you will frame the problem you encountered and how you plan to solve it.

### Data and Methods 

Here you will describe the data discoversy process, the data used, and the methods employed to solve your problem. 

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(collapsibleTree)
library(tidyverse)
OSS <- data.frame(
    Sector = c(
        "Academic", "Academic","Academic", "Academic", "Academic", "Academic","Academic","Academic","Academic","Academic","Academic","Academic","Academic","Academic","Academic","Academic","Academic","Academic","Academic",
        
        "Business","Business","Business","Business","Business", "Business", "Business", "Business", "Business", "Business","Business","Business", "Business",
        
        "Government", "Government","Government", "Government","Government","Government","Government", "Government", "Government","Government", "Government", "Government",
        
        "International","International","International"
    ),
    DataSource = c(
      #academic
        "github","github", "github","github","github",
        "orcid", 
        "hipolabs", "hipolabs","hipolabs",
        "NCSES","NCSES", "NCSES", "NCSES","NCSES", "NCSES", "NCSES","NCSES", "NCSES","NCSES",
        
      #business
      "github","github", 
      "Enterprise-Driven OSS", "Enterprise-Driven OSS",  
      "forbes",  "forbes", "forbes", 
      "Global Legal Entity Identifier Foundation (GLEIF)", 
      "Data Hub", "Data Hub", "Data Hub", 
      "2020 US Business Database",
      
    #gov  
        "github","github", "System for Award Management (SAM)", "System for Award Management (SAM)","System for Award Management (SAM)","us gov","us gov","us gov","us gov","us gov","us gov", "code gov", "crowdsourced",
     
     #international
       "github","github", "mindmap"
    ),
    SubData = c(
      #academic
        "contributor","contributor","contributor","contributor","commits", 
        "orcid", 
        "hipolabs", "hipolabs","hipolabs",
        "Survey of Federal Science and Engineering Support 2018", "Survey of Federal Science and Engineering Support 2018", "Survey of Federal Science and Engineering Support 2018", "Survey of Federal Science and Engineering Support 2018", "Higher Education Research and Development Survey 2018", "Higher Education Research and Development Survey 2018", "Higher Education Research and Development Survey 2018", "Higher Education Research and Development Survey 2018", "Higher Education Research and Development Survey 2018", "Higher Education Research and Development Survey 2018", 
        
      #business
        "contributor", "commits", 
      "cohort project details", "enterprise project",
      "Fortune's Annual Ranking of Companies 2018 (US 1000)", "Fortune's Annual Ranking of Companies 2019 (US 1000)", "Fortune's Annual Ranking of Companies 2020 (Global 2000)", 
      "GLEIF", 
      "email domains",  "email domains", "email domains", 
      "2020 US Business Database",
        
      #gov
        "contributor", "commits", 
        "System for Award Management (SAM)","System for Award Management (SAM)","System for Award Management (SAM)","Federally Funded R&D Centers", "Federally Funded R&D Centers", 
        "A-Z Index","A-Z Index", "A-Z Index","A-Z Index",
        "code gov", "crowdsourced", 
    
      #international    
        "contributor", "commits", "mindmap"
    ),
    Variables = c(
        "login", "email","organization","company","commits",
        "orcid", 
        "institution",
        "country",
        "domains",
        "institution", "rank","all federal obligations" , "R&D", "institution", "rank", "R&D expenditure", "federal gov fund", "state local gov fund", "institution funds",
        
        "contributor", "commits", 
        "cohort project details", "enterprise project", 
        "Fortune's Annual Ranking of Companies 2018 (US 1000)", "Fortune's Annual Ranking of Companies 2019 (US 1000)", "Fortune's Annual Ranking of Companies 2020 (Global 2000)", 
        "country", 
        "domain", "type", "organization", "2020 US Business Database",
        
        "contributor", "commits",  "parent","fhorgtype", "fhorgname", "ffrdc name", "agency", "agency", "gov branch", "parent agency", "parent agency parent", "code gov", "crowdsourced", 
        
        "contributor", "commits", "mindmap"
    )
)

# Collapsible Tree
                                    
collapsibleTree(OSS, 
                c("Sector", "DataSource", "SubData", "Variables"), 
                collapsed = T,
                fill ="#E57200"
)

```

### Main Findings 

Here you will describe the results and include important visualizations from your project. 

### Conclusion and Policy Implications 

Here you could highlight the main takeaways and the potential policy implications of your findings. 

### References 

List your references here using APA format (or at least standardize all of the references using the same format).







